---
- name: PPA repo for Munin (later versions)
  apt_repository: 
    repo: 'ppa:pneu/munin'

- name: Install required packages for munin.
  apt: 
    pkg: "{{ item }}"
    state: installed
  with_items: munin_packages

- name: Copy munin configurations.
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: munin.conf.j2, dest: /etc/munin/munin.conf }
    - { src: hosts.conf.j2, dest: "{{ munin_conf_d_directory }}/hosts.conf" }

- name: Create munin user via htpasswd.
  htpasswd:
    create: yes
    name: "{{ munin_admin_user }}"
    password: "{{ munin_admin_password }}"
    path: /etc/munin/munin-htpasswd
    state: present

- name: Enable or disable the munin cron job.
  lineinfile:
    dest: /etc/cron.d/munin
    state: "{{ munin_cron_job }}"
    regexp: "^\\*/5 \\* \\* \\* \\*"
    line: "*/5 * * * *     munin test -x /usr/bin/munin-cron && /usr/bin/munin-cron"

- name: set up nginx config
  copy:
    src: nginx-munin.conf
    dest: /etc/nginx/sites-available/munin
  notify: restart nginx

- name: symlink nginx config
  file:
    src: /etc/nginx/sites-available/munin
    dest: /etc/nginx/sites-enabled/munin
    state: link
  notify: restart nginx

- name: ensure munin-cgi-html defaults
  copy:
    src: munin-cgi-html.default.conf
    dest: /etc/default/munin-cgi-html
  notify: restart munin-cgi-html

- name: ensure munin-cgi-html upstart script
  copy:
    src: munin-cgi-html.upstart.conf
    dest: /etc/init/munin-cgi-html.conf
  notify: restart munin-cgi-html

- name: symlink munin-cgi-html init script
  file:
    src: /lib/init/upstart-job
    dest: /etc/init.d/munin-cgi-html
    state: link
  notify: restart munin-cgi-html

- name: ensure munin-cgi-graph defaults
  copy:
    src: munin-cgi-graph.default.conf
    dest: /etc/default/munin-cgi-graph
  notify: restart munin-cgi-graph

- name: ensure munin-cgi-graph upstart script
  copy:
    src: munin-cgi-graph.upstart.conf
    dest: /etc/init/munin-cgi-graph.conf
  notify: restart munin-cgi-graph

- name: symlink munin-cgi-graph init script
  file:
    src: /lib/init/upstart-job
    dest: /etc/init.d/munin-cgi-graph
    state: link
  notify: restart munin-cgi-graph

- name: ensure munin-cgi-html service state
  service:
    name: munin-cgi-html
    state: "{{ munin_cgi_html_service_state }}"

- name: ensure munin-cgi-graph service state
  service:
    name: munin-cgi-graph
    state: "{{ munin_cgi_graph_service_state }}"
